name: Run examples and tests

on:
  push:
    branches:
      - main
      - yagna/master
  pull_request:
    branches:
      - main
      - yagna/master
  workflow_dispatch:

jobs:
  run-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the SDK repo
        uses: actions/checkout@v4

      - name: Setup Go, Rust and Golem Base
        uses: ./.github/workflows/setup

    #   - name: Run Rust demo example
    #     run: cargo run
    #     working-directory: ./demo

      - name: Run Rust yagna interaction example
        run: cargo run --example yagna_interaction

  run-tests-and-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the SDK repo
        uses: actions/checkout@v4

      - name: Setup Go, Rust and Golem Base
        uses: ./.github/workflows/setup

      - name: Run tests
        env:
          RUST_TEST_THREADS: 1
          TEST_ENABLE_ALL_LOGS_OVERRIDE: true
          RUST_LOG: debug
        run: cargo test --workspace -- --test-threads=1

      - name: Build docs
        run: cargo doc --no-deps --workspace

      - name: Deploy docs to branch folder
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          publish_branch: gh-pages
          destination_dir: ${{ github.head_ref }}

      - name: Comment PR with docs URL
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Preview the generated documentation for this PR at:
            https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.head_ref }}/golem_base_sdk/
